### ISSUE TITLE
Ordering instructions

### ISSUE THREAD

**Issue by xRealNeon** [Envious-Data/Env-KB#1]
Can you add some instructions how to order the PCB with SMT from jlc.

**Comment by Envious-Data** [comment]
I have added a guide here
https://github.com/Envious-Data/Env-KB/blob/main/_docs/Ordering_my_PCBs_via_JLCPCB.pdf

let me know if it makes enough sense 👍

**Comment by xRealNeon** [comment]
Yeah, thx for that
